/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartComponent: typeof import('./src/components/ChartComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBarComponent: typeof import('./src/components/HeaderBarComponent.vue')['default']
    InstrumentItemComponent: typeof import('./src/components/InstrumentItemComponent.vue')['default']
    InstrumentListComponent: typeof import('./src/components/InstrumentListComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBarComponent: typeof import('./src/components/SearchBarComponent.vue')['default']
    SummaryComponent: typeof import('./src/components/SummaryComponent.vue')['default']
    TabComponent: typeof import('./src/components/TabComponent.vue')['default']
  }
}
